### ISSUE TITLE
能否增加注记图层

### ISSUE THREAD

**Issue by ghost** [baxtergu/arcgis-jsapi4-load-tianditu-wmts-service#1]

**Comment by baxtergu** [comment]
你好，如果想要添加其他的天地图地图瓦片图层的话，可以在 `TdtUrlTemplates.js` 中的返回对象中添加相应瓦片图层的请求模板，然后使用请求模板和TileInfo来初始化一个新的图层添加到MapView中去。天地图官方的瓦片地图请求模板可以在网上搜到，这里就不单独提供了。

**Comment by baxtergu** [comment]
![image](https://user-images.githubusercontent.com/2825625/34856382-b199cf02-f77f-11e7-82e8-a4a28c6909d3.png)

**Comment by baxtergu** [comment]
请参照以下代码的URL规则来寻找合适的切片地址
```javascript
var urlTemplatesObject = {
    TDT: "http://{subDomain}.tianditu.com/vec_c/wmts?SERVICE=WMTS&request=GetTile&version=1.0.0&LAYER=vec&tileMatrixSet=c&TileMatrix={level}&TileRow={row}&TileCol={col}&style=default&format=tiles"
  };
```
